[package]
name = "tcp_lb_rs"
version = "0.1.0"
authors = ["mutalisk <0x08@0x08.net>"]
edition = "2018"

[dependencies]
tokio = { version = "1.2.0", features = ["full"] }
toml = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"


